#!/usr/bin/env python3
#
# Useful WiX resources:
# - https://stackoverflow.com/questions/471424/wix-tricks-and-tips
#

from xml.dom.minidom import getDOMImplementation
import uuid
import subprocess
import hashlib
import os
from pathlib import Path

# Converts any string identifier into a valid WiX Id, that is:
# - only contain ASCII characters A-Z, a-z, digits, underscores, or period,
# - begin with either a letter or an underscore
# - is 72 characters or less
# - is 57 characters or less if it is an Icon Id.
#
# For now we do this by computing a md5 hash (prepended with an underscore
# otherwise the hash may start with a digit which is forbidden). In the
# future, to make the ID more human friendly, we may use a combination
# of hash (for uniqueness), but still with the input ID as intact as possible.
#
def encodeId(s):
    return "_" + hashlib.md5(s.encode('utf-8')).hexdigest()

# This is a convenient class to generate a wxs file to be compiled
# with WiX. Traditionally, these are generated by using WiX tools such
# as 'heat', but we prefer the flexibility of a real programming language
# such as Python for this.
#
# Note that this is just a first iteration, and the API isn't that
# nice for now. In the future, we might want to have a more user
# friendly API with more classes, in order to do things like:
#
#   cmp = dir.createComponent("MyComponent")
#
# instead of:
#
#   cmp = wix.createChild(dir, "Component", [
#       ("Id", "MyComponent"),
#       ("Guid", wix.staticGuid("Component/MyComponent"))])
#
# Note on "Id" identifiers: for the most part, we automatically generate
# them from the other arguments we have. We convert special characters into
# underscore, due to the following constraints:
#
#
class Wix:

    # Creates a new Wix XML document with the following automatically
    # generated WixElements:
    # - wix.root: the root Wix element
    # - wix.product: the Product element
    # - wix.package: the Package element
    # - wix.media: the Media element
    #
    # And the following directories:
    # - wix.targetDirectory: the root of the selected install disk (e.g., "C:")
    # - wix.programFilesDirectory: "Program Files" directory
    # - wix.manufacturerDirectory: "Program Files\[Manufacturer]"
    # - wix.installDirectory:      "Program Files\[Manufacturer]\[ProductName]"
    # - wix.startMenuDirectory:    Windows' Start Menu
    # - wix.desktopDirectory:      Windows' desktop
    #
    def __init__(self, name, version, manufacturer, wixDir, win64 = True):
        self.name = name
        self.version = version
        self.manufacturer = manufacturer
        self.wixDir = wixDir
        self.win64 = win64
        if self.win64:
            self.win64yesno = "yes"
            self.platform = "x64"
            programFilesFolder = "ProgramFiles64Folder"
        else:
            self.win64yesno = "no"
            self.platform = "x86"
            programFilesFolder = "ProgramFilesFolder"

        # Create XML document.
        #
        domImplementation = getDOMImplementation()
        self.domDocument = domImplementation.createDocument(None, "Wix", None)

        # Get Wix root element and set its xmlns attribute.
        #
        self.root = WixElement(self.domDocument.documentElement, self, "")
        self.root.setAttribute("xmlns", "http://schemas.microsoft.com/wix/2006/wi")

        # Add product. Note that we regenerate its ProductCode GUID
        # (= 'Id' attribute) when the version change since we consider all
        # changes of version to be "Major Upgrades" in MSI terminology. We need
        # this since components may be added, moved or removed even when going
        # from VGC 2020.0 to VGC 2020.1. Also, we desire that the name of our
        # MSI file changes in this case, and it is a Microsoft requirement to
        # keep the same MSI filename during a "Minor Upgrade" or "Small Uprade".
        #
        # TODO: prettify display name to something like:
        #   VGC Illustration Daily Beta 2019-05-27 R2
        #
        self.product = self.root.createChild("Product", [
            ("Name", name + " " + version),
            ("Id", self.dynamicGuid("Product/ProductCode")),
            ("UpgradeCode", self.staticGuid("Product/UpgradeCode")),
            ("Language", "1033"),
            ("Codepage", "1252"),
            ("Version", version),
            ("Manufacturer", manufacturer)])

        # Add package
        #
        # Note: candle.exe emits a warning if we manually assigns an Id (e.g.,
        # wix.dynamicGuid("Package/Id")), which is why we use "*" here.
        #
        # Note 2: manual specification of "Platform" is discouraged in favour
        # of using the candle.exe -arch x64/x86 switch, but we use both anyway.
        #
        self.package = self.product.createChild("Package", [
            ("Id", "*"),
            ("Keywords", "Installer"),
            ("Description", "Installer of " + name + " " + version),
            ("Manufacturer", manufacturer),
            ("InstallerVersion", "500"),
            ("Languages", "1033"),
            ("Compressed", "yes"),
            ("SummaryCodepage", "1252"),
            ("Platform", self.platform)])

        # Add media
        self.media = self.product.createChild("Media", [
            ("Id", "1"),
            ("Cabinet", "Cabinet.cab"),
            ("EmbedCab", "yes")])

        # Add basic directory structure. As far as I understand, a lot of these
        # Name and Id attribute are "magic names" recognized by either WiX or
        # Windows Installer, and can't be changed.
        self.targetDirectory = self.product.createDirectory("SourceDir", "TARGETDIR")
        self.programFilesDirectory = self.targetDirectory.createDirectory("PFiles", programFilesFolder)
        self.manufacturerDirectory = self.programFilesDirectory.createDirectory(manufacturer)
        self.installDirectory = self.manufacturerDirectory.createDirectory(name, "INSTALLDIR")
        self.startMenuDirectory = self.targetDirectory.createDirectory("Programs", "ProgramMenuFolder")
        self.desktopDirectory = self.targetDirectory.createDirectory("Desktop", "DesktopFolder")

    # Generates a deterministic GUID based on the current productName,
    # productVersion, and given string identifier "sid". This GUID
    # changes from version to version even if the productName and sid
    # don't change.
    #
    def dynamicGuid(self, sid):
        u = uuid.uuid5(uuid.NAMESPACE_URL,
                  "http://dynamicguid.wix.vgc.io" +
                  "/" + self.name +
                  "/" + self.version +
                  "/" + sid)
        return str(u).upper()

    # Generates a deterministic GUID based on the current productName and
    # given string identifier "sid". This GUID is unchanged from version to
    # version as long as the productName and sid don't change.
    #
    def staticGuid(self, sid):
        u = uuid.uuid5(uuid.NAMESPACE_URL,
                  "http://staticguid.wix.vgc.io" +
                  "/" + self.name +
                  "/" + sid)
        return str(u).upper()

    # Generates the MSI file
    #
    def makeMsi(self, msiPath):
        wxs = msiPath.with_suffix(".wxs")
        wixobj = msiPath.with_suffix(".wixobj")
        msi = msiPath.with_suffix(".msi")
        binDir = self.wixDir / "bin"

        # Generate the .wxs file
        wxs.write_bytes(self.domDocument.toprettyxml(encoding='windows-1252'))

        # Generate the .wxsobj file
        subprocess.run([
            str(binDir / "candle.exe"), str(wxs),
            "-arch", self.platform,
            "-out", str(wixobj)])

        # Generate the .msi file
        # ICE07/ICE60: Remove warnings about font files. See:
        # https://stackoverflow.com/questions/13052258/installing-a-font-with-wix-not-to-the-local-font-folder
        subprocess.run([
            str(binDir / "light.exe"), str(wixobj),
            "-sice:ICE07", "-sice:ICE60",
            "-out", str(msi)])

    # Creates a new feature. Note: feature names cannot be longer than 38 characters in length.
    #
    def createFeature(self, name, level = 1):
        return self.product.createChild("Feature", [
            ("Id", name),
            ("Level", str(level))])

    # Creates a new icon.
    #
    def createIcon(self, srcFile):
        # Note: icon Ids must end with either .ico or .exe
        # and match the extension of the filename.
        basename = srcFile.with_suffix("").name
        suffix = srcFile.suffix
        iconId = encodeId("Icon" + basename) + suffix
        icon = self.product.createChild("Icon", [
            ("Id", iconId),
            ("SourceFile", str(srcFile))])
        icon.iconId = iconId
        return icon

# A WixElement represents an XML element in the WiX file.
# It is a wrapper around dom.Element providing more convenient API.
#
class WixElement:

    # Wraps a dom.Element into a WixElement. This is an implementation detail,
    # clients are not supposed to call this themselves, but instead to use the
    # WixElement.createChild() function.
    #
    def __init__(self, domElement, wix, dirId):
        self.domElement = domElement
        self.wix = wix
        self.dirId = dirId

    # Sets the attribute of this WixElement
    #
    def setAttribute(self, name, value):
         self.domElement.setAttribute(name, value)

    # Gets the value of the given attribute of this WixElement
    #
    def getAttribute(self, name):
         self.domElement.getAttribute(name)

    # Creates a new Element with the given tagName, and appends this new
    # Element as a child of the given parent Element. Returns the new Element.
    #
    def createChild(self, tagName, attributes):
        domChild = self.wix.domDocument.createElement(tagName)
        self.domElement.appendChild(domChild)
        child = WixElement(domChild, self.wix, self.dirId)
        for pair in attributes:
            child.setAttribute(pair[0], pair[1])
        return child

    # Creates a new Directory with the given name and the given ID.
    # If no ID is provided, one will be automatically generated.
    #
    def createDirectory(self, name, dirId = None):
        if dirId is None:
            dirId = encodeId(self.dirId + '/' + name)
        child = self.createChild("Directory", [("Id", dirId), ("Name", name)])
        child.dirId = dirId
        child.files = {}
        return child

    # Creates a shortcut to this file using the given icon
    #
    def createShortcut(self, directory, name, icon, workingDirectory = None):
        if workingDirectory is None:
            workingDirectory = self.wix.installDirectory
        return self.createChild("Shortcut", [
            ("Id", encodeId("Shortcut" + directory.dirId + "/" + name)),
            ("Directory", directory.dirId),
            ("Name", name),
            ("WorkingDirectory", workingDirectory.dirId),
            ("Icon", icon.iconId),
            ("IconIndex", "0"),
            ("Advertise", "yes")])

    # Creates a submenu of the startup menu.
    # It has to be associated with a feature so that it is deleted when the
    # feature is uninstalled.
    #
    def createSubMenu(self, name, feature):
        subMenuDirectory = self.createDirectory(name)
        componentId = encodeId("SubMenuComponent" + subMenuDirectory.dirId)
        subMenuComponent = subMenuDirectory.createChild("Component", [
            ("Id", componentId),
            ("Guid", self.wix.staticGuid(componentId))])
        subMenuComponent.createChild("RemoveFolder", [
            ("Id", encodeId("RemoveFolder" + componentId)),
            ("On", "uninstall")])
        subMenuComponent.createChild("RegistryValue", [
            ("Root", "HKCU"),
            ("Key", "Software\\[Manufacturer]\\[ProductName]"),
            ("Type", "string"),
            ("Value", ""),
            ("KeyPath", "yes")])
        feature.createChild("ComponentRef", [("Id", componentId)])
        return subMenuDirectory

    # Creates a file.
    #
    def createFile(self, srcFile, name, feature):
        componentId = encodeId("FileComponent" + self.dirId + "/" + name)
        fileComponent = self.createChild("Component", [
            ("Id", componentId),
            ("Guid", self.wix.staticGuid(componentId)),
            ("Win64", self.wix.win64yesno)])
        file = fileComponent.createChild("File", [
            ("Id", encodeId("File" + componentId)),
            ("Name", name),
            ("DiskId", "1"),
            ("Source", str(srcFile)),
            ("KeyPath", "yes")])
        self.files[name] = file
        feature.createChild("ComponentRef", [("Id", componentId)])
        return file

    # Returns a previously created file
    #
    def getFile(self, name):
        return self.files[name]

    # Recursively add the given directory and all its files to this directory
    # for the given feature
    #
    def addDirectory(self, srcDir, feature):
        destDir = self.createDirectory(srcDir.name)
        for child in srcDir.iterdir():
            if child.is_file():
                destDir.createFile(str(child), child.name, feature)
            elif child.is_dir():
                destDir.addDirectory(child, feature)
        return destDir

# Generates an MSI file from the build
#
def run(buildDir, config, wixDir):
    buildDir = Path(buildDir)
    wixDir = Path(wixDir)
    configDir = buildDir / config
    deployDir = configDir / "deploy"
    deployDir.mkdir(parents=True, exist_ok=True)

    # General configuration
    productName = "VGC Illustration Daily Beta"
    version = "19.5.27.1"
    manufacturer = "VGC Software"
    wix = Wix(productName, version, manufacturer, wixDir)
    feature = wix.createFeature("Complete")

    # Add 'bin', 'python', and 'resources' directories
    wixBinDir = wix.installDirectory.addDirectory(configDir / "bin", feature)
    wix.installDirectory.addDirectory(configDir / "python", feature)
    wix.installDirectory.addDirectory(configDir / "resources", feature)

    # Create Desktop and Start Menu shortcuts
    executable = wixBinDir.getFile("vgcillustration.exe")
    icon = wix.createIcon(buildDir / "vgcillustration.ico")
    executable.createShortcut(wix.startMenuDirectory, productName, icon)
    executable.createShortcut(wix.desktopDirectory, productName, icon)

    # Generate the MSI file
    wix.makeMsi(deployDir / "vgcillustration.msi")

    # TODO: implement Gui
    # TODO: bundle in a .exe that runs vs_redist.x64.exe if required
