
# See https://www.appveyor.com/docs/appveyor-yml/ for reference

version: 1.0.{build}
image: Visual Studio 2017
clone_folder: C:/dev/vgc
shallow_clone: false
clone_depth: 50
platform: x64
configuration: Release

before_build:
  - echo %APPVEYOR_PULL_REQUEST_NUMBER%
  - echo %APPVEYOR_PULL_REQUEST_TITLE%
  - echo %APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME%
  - echo %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%
  - echo %APPVEYOR_PULL_REQUEST_HEAD_COMMIT%
  - echo %APPVEYOR_REPO_NAME%
  - echo %APPVEYOR_REPO_BRANCH%
  - echo %APPVEYOR_REPO_COMMIT%
  - echo %APPVEYOR_REPO_COMMIT_MESSAGE%
  - echo %APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%
  - if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (set VGC_COMMIT_BRANCH=%APPVEYOR_REPO_BRANCH%) else (set VGC_COMMIT_BRANCH=%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%)
  - echo %VGC_COMMIT_BRANCH%
  - cd C:/dev
  - mkdir build
  - cd build
  - cmake ../vgc -G "Visual Studio 15 2017" -A x64 -DPython="C:/Python37-x64" -DQt="C:/Qt/5.12.4/msvc2017_64" -DWiX="C:/Program Files (x86)/WiX Toolset v3.11" -DVGC_COMMIT_BRANCH=%VGC_COMMIT_BRANCH%

build_script:
  - cd C:/dev/build
  - make
  - make deploy

test_script:
  - cd C:/dev/build
  - test -VV
