
# See https://www.appveyor.com/docs/appveyor-yml/ for reference

version: 1.0.{build}
image: Visual Studio 2017
clone_folder: C:/dev/vgc
shallow_clone: false
clone_depth: 50
platform: x64
configuration: Release

before_build:
  - cd C:/dev
  - mkdir build
  - cd build
  - cmake ../vgc -G "Visual Studio 15 2017" -A x64 -DPython="C:/Python37-x64" -DQt="C:/Qt/5.12.4/msvc2017_64" -DWiX="C:/Program Files (x86)/WiX Toolset v3.11"

build:
  parallel: true
  project: C:/dev/build/ALL_BUILD.vcxproj
  verbosity: minimal
