// Copyright 2022 The VGC Developers
// See the COPYRIGHT file at the top-level directory of this distribution
// and at https://github.com/vgc/vgc/blob/master/COPYRIGHT
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <vgc/ui/key.h>

namespace vgc::ui {

VGC_DEFINE_ENUM_BEGIN(Key)
    VGC_ENUM_VALUE(None, "None")

    // ASCII
    VGC_ENUM_VALUE(Space, "Space")
    VGC_ENUM_VALUE(Exclamation, "!")
    VGC_ENUM_VALUE(DoubleQuote, "\"")
    VGC_ENUM_VALUE(Hashtag, "#")
    VGC_ENUM_VALUE(Dollar, "$")
    VGC_ENUM_VALUE(Percent, "%")
    VGC_ENUM_VALUE(Ampersand, "&")
    VGC_ENUM_VALUE(Apostrophe, "'")
    VGC_ENUM_VALUE(LeftParenthesis, "(")
    VGC_ENUM_VALUE(RightParenthesis, ")")
    VGC_ENUM_VALUE(Asterisk, "*")
    VGC_ENUM_VALUE(Plus, "+")
    VGC_ENUM_VALUE(Comma, ",")
    VGC_ENUM_VALUE(Minus, "-")
    VGC_ENUM_VALUE(Period, ".")
    VGC_ENUM_VALUE(Slash, "/")
    VGC_ENUM_VALUE(Digit0, "0")
    VGC_ENUM_VALUE(Digit1, "1")
    VGC_ENUM_VALUE(Digit2, "2")
    VGC_ENUM_VALUE(Digit3, "3")
    VGC_ENUM_VALUE(Digit4, "4")
    VGC_ENUM_VALUE(Digit5, "5")
    VGC_ENUM_VALUE(Digit6, "6")
    VGC_ENUM_VALUE(Digit7, "7")
    VGC_ENUM_VALUE(Digit8, "8")
    VGC_ENUM_VALUE(Digit9, "9")
    VGC_ENUM_VALUE(Colon, ":")
    VGC_ENUM_VALUE(Semicolon, ";")
    VGC_ENUM_VALUE(LessThan, "<")
    VGC_ENUM_VALUE(Equal, "=")
    VGC_ENUM_VALUE(GreaterThan, ">")
    VGC_ENUM_VALUE(Question, "?")
    VGC_ENUM_VALUE(At, "@")
    VGC_ENUM_VALUE(A, "A")
    VGC_ENUM_VALUE(B, "B")
    VGC_ENUM_VALUE(C, "C")
    VGC_ENUM_VALUE(D, "D")
    VGC_ENUM_VALUE(E, "E")
    VGC_ENUM_VALUE(F, "F")
    VGC_ENUM_VALUE(G, "G")
    VGC_ENUM_VALUE(H, "H")
    VGC_ENUM_VALUE(I, "I")
    VGC_ENUM_VALUE(J, "J")
    VGC_ENUM_VALUE(K, "K")
    VGC_ENUM_VALUE(L, "L")
    VGC_ENUM_VALUE(M, "M")
    VGC_ENUM_VALUE(N, "N")
    VGC_ENUM_VALUE(O, "O")
    VGC_ENUM_VALUE(P, "P")
    VGC_ENUM_VALUE(Q, "Q")
    VGC_ENUM_VALUE(R, "R")
    VGC_ENUM_VALUE(S, "S")
    VGC_ENUM_VALUE(T, "T")
    VGC_ENUM_VALUE(U, "U")
    VGC_ENUM_VALUE(V, "V")
    VGC_ENUM_VALUE(W, "W")
    VGC_ENUM_VALUE(X, "X")
    VGC_ENUM_VALUE(Y, "Y")
    VGC_ENUM_VALUE(Z, "Z")
    VGC_ENUM_VALUE(LeftSquareBracket, "[")
    VGC_ENUM_VALUE(Backslash, "\\")
    VGC_ENUM_VALUE(RightSquareBracket, "]")
    VGC_ENUM_VALUE(Circumflex, "^")
    VGC_ENUM_VALUE(Underscore, "_")
    VGC_ENUM_VALUE(BackQuote, "`")
    VGC_ENUM_VALUE(LeftCurlyBracket, "{")
    VGC_ENUM_VALUE(VerticalLine, "|")
    VGC_ENUM_VALUE(RightCurlyBracket, "}")
    VGC_ENUM_VALUE(Tilde, "~")

    // Latin-1 Supplement
    //
    // TODO: Should some of the pretty names be in lowercase?
    //       Example, on French AZERTY keyboard: ç, ù, é, è, à
    //       Perhaps the key pretty name should depend on the locale
    //       What about Print Screen / Impr Écran ?
    //
    VGC_ENUM_VALUE(NoBreakSpace, "Nbsp")
    VGC_ENUM_VALUE(InvertedExclamation, "¡")
    VGC_ENUM_VALUE(Cent, "¢")
    VGC_ENUM_VALUE(Pound, "£")
    VGC_ENUM_VALUE(Currency, "¤")
    VGC_ENUM_VALUE(Yen, "¥")
    VGC_ENUM_VALUE(BrokenBar, "¦")
    VGC_ENUM_VALUE(Section, "§")
    VGC_ENUM_VALUE(Diaeresis, "¨")
    VGC_ENUM_VALUE(Copyright, "©")
    VGC_ENUM_VALUE(FeminineOrdinal, "ª")
    VGC_ENUM_VALUE(LeftGuillemet, "«")
    VGC_ENUM_VALUE(NotSign, "¬")
    VGC_ENUM_VALUE(SoftHyphen, "Shy")
    VGC_ENUM_VALUE(Registered, "®")
    VGC_ENUM_VALUE(Macron, "¯")
    VGC_ENUM_VALUE(Degree, "°")
    VGC_ENUM_VALUE(PlusMinus, "±")
    VGC_ENUM_VALUE(SuperscriptTwo, "²")
    VGC_ENUM_VALUE(SuperscriptThree, "³")
    VGC_ENUM_VALUE(Acute, "´")
    VGC_ENUM_VALUE(Mu, "µ")
    VGC_ENUM_VALUE(Paragraph, "¶")
    VGC_ENUM_VALUE(MiddleDot, "·")
    VGC_ENUM_VALUE(Cedilla, "¸")
    VGC_ENUM_VALUE(SuperscriptOne, "¹")
    VGC_ENUM_VALUE(MasculineOrdinal, "º")
    VGC_ENUM_VALUE(RightGuillemet, "»")
    VGC_ENUM_VALUE(OneQuarter, "¼")
    VGC_ENUM_VALUE(OneHalf, "½")
    VGC_ENUM_VALUE(ThreeQuarters, "¾")
    VGC_ENUM_VALUE(InvertedQuestion, "¿")
    VGC_ENUM_VALUE(AGrave, "À")
    VGC_ENUM_VALUE(AAcute, "Á")
    VGC_ENUM_VALUE(ACircumflex, "Â")
    VGC_ENUM_VALUE(ATilde, "Ã")
    VGC_ENUM_VALUE(ADiaeresis, "Ä")
    VGC_ENUM_VALUE(ARing, "Å")
    VGC_ENUM_VALUE(Ae, "Æ")
    VGC_ENUM_VALUE(CCedilla, "Ç")
    VGC_ENUM_VALUE(EGrave, "È")
    VGC_ENUM_VALUE(EAcute, "É")
    VGC_ENUM_VALUE(ECircumflex, "Ê")
    VGC_ENUM_VALUE(EDiaeresis, "Ë")
    VGC_ENUM_VALUE(IGrave, "Ì")
    VGC_ENUM_VALUE(IAcute, "Í")
    VGC_ENUM_VALUE(ICircumflex, "Î")
    VGC_ENUM_VALUE(IDiaeresis, "Ï")
    VGC_ENUM_VALUE(Eth, "Ð")
    VGC_ENUM_VALUE(NTilde, "Ñ")
    VGC_ENUM_VALUE(OGrave, "Ò")
    VGC_ENUM_VALUE(OAcute, "Ó")
    VGC_ENUM_VALUE(OCircumflex, "Ô")
    VGC_ENUM_VALUE(OTilde, "Õ")
    VGC_ENUM_VALUE(ODiaeresis, "Ö")
    VGC_ENUM_VALUE(Multiplication, "×")
    VGC_ENUM_VALUE(OStroke, "Ø")
    VGC_ENUM_VALUE(UGrave, "Ù")
    VGC_ENUM_VALUE(UAcute, "Ú")
    VGC_ENUM_VALUE(UCircumflex, "Û")
    VGC_ENUM_VALUE(UDiaeresis, "Ü")
    VGC_ENUM_VALUE(YAcute, "Ý")
    VGC_ENUM_VALUE(Thorn, "Þ")
    VGC_ENUM_VALUE(SSharp, "ß")
    VGC_ENUM_VALUE(Division, "÷")
    VGC_ENUM_VALUE(YDiaeresis, "ÿ")

    // Common keys
    VGC_ENUM_VALUE(Escape, "Esc")
    VGC_ENUM_VALUE(Tab, "Tab")
    VGC_ENUM_VALUE(Backtab, "Backtab")
    VGC_ENUM_VALUE(Backspace, "Backspace")
    VGC_ENUM_VALUE(Return, "Return")
    VGC_ENUM_VALUE(Enter, "Enter")
    VGC_ENUM_VALUE(Insert, "Insert")
    VGC_ENUM_VALUE(Delete, "Del")
    VGC_ENUM_VALUE(Pause, "Pause")
    VGC_ENUM_VALUE(PrintScreen, "PrtSc")
    VGC_ENUM_VALUE(SysRq, "SysRq")
    VGC_ENUM_VALUE(Clear, "Clear")
    VGC_ENUM_VALUE(Home, "Home")
    VGC_ENUM_VALUE(End, "End")
    VGC_ENUM_VALUE(Left, "Left")
    VGC_ENUM_VALUE(Up, "Up")
    VGC_ENUM_VALUE(Right, "Right")
    VGC_ENUM_VALUE(Down, "Down")
    VGC_ENUM_VALUE(PageUp, "PgUp")
    VGC_ENUM_VALUE(PageDown, "PgDown")

    // Modifier keys
    VGC_ENUM_VALUE(Shift, "Shift")
    VGC_ENUM_VALUE(Ctrl, "Ctrl")
    VGC_ENUM_VALUE(Meta, "Meta")
    VGC_ENUM_VALUE(Alt, "Alt")

    // Lock keys
    VGC_ENUM_VALUE(CapsLock, "CapsLock")
    VGC_ENUM_VALUE(NumLock, "NumLock")
    VGC_ENUM_VALUE(ScrollLock, "ScrollLock")

    // Function keys
    VGC_ENUM_VALUE(F1, "F1")
    VGC_ENUM_VALUE(F2, "F2")
    VGC_ENUM_VALUE(F3, "F3")
    VGC_ENUM_VALUE(F4, "F4")
    VGC_ENUM_VALUE(F5, "F5")
    VGC_ENUM_VALUE(F6, "F6")
    VGC_ENUM_VALUE(F7, "F7")
    VGC_ENUM_VALUE(F8, "F8")
    VGC_ENUM_VALUE(F9, "F9")
    VGC_ENUM_VALUE(F10, "F10")
    VGC_ENUM_VALUE(F11, "F11")
    VGC_ENUM_VALUE(F12, "F12")
    VGC_ENUM_VALUE(F13, "F13")
    VGC_ENUM_VALUE(F14, "F14")
    VGC_ENUM_VALUE(F15, "F15")
    VGC_ENUM_VALUE(F16, "F16")
    VGC_ENUM_VALUE(F17, "F17")
    VGC_ENUM_VALUE(F18, "F18")
    VGC_ENUM_VALUE(F19, "F19")
    VGC_ENUM_VALUE(F20, "F20")
    VGC_ENUM_VALUE(F21, "F21")
    VGC_ENUM_VALUE(F22, "F22")
    VGC_ENUM_VALUE(F23, "F23")
    VGC_ENUM_VALUE(F24, "F24")
    VGC_ENUM_VALUE(F25, "F25")
    VGC_ENUM_VALUE(F26, "F26")
    VGC_ENUM_VALUE(F27, "F27")
    VGC_ENUM_VALUE(F28, "F28")
    VGC_ENUM_VALUE(F29, "F29")
    VGC_ENUM_VALUE(F30, "F30")
    VGC_ENUM_VALUE(F31, "F31")
    VGC_ENUM_VALUE(F32, "F32")
    VGC_ENUM_VALUE(F33, "F33")
    VGC_ENUM_VALUE(F34, "F34")
    VGC_ENUM_VALUE(F35, "F35")

    // Other keys below

    VGC_ENUM_VALUE(LeftSuper, "LeftSuper")
    VGC_ENUM_VALUE(RightSuper, "RightSuper")
    VGC_ENUM_VALUE(Menu, "Menu")
    VGC_ENUM_VALUE(LeftHyper, "LeftHyper")
    VGC_ENUM_VALUE(RightHyper, "RightHyper")
    VGC_ENUM_VALUE(Help, "Help")
    VGC_ENUM_VALUE(LeftDirection, "LeftDirection")
    VGC_ENUM_VALUE(RightDirection, "RightDirection")

    VGC_ENUM_VALUE(Back, "Back")
    VGC_ENUM_VALUE(Forward, "Forward")
    VGC_ENUM_VALUE(Stop, "Stop")
    VGC_ENUM_VALUE(Refresh, "Refresh")

    VGC_ENUM_VALUE(VolumeDown, "VolumeDown")
    VGC_ENUM_VALUE(VolumeMute, "VolumeMute")
    VGC_ENUM_VALUE(VolumeUp, "VolumeUp")
    VGC_ENUM_VALUE(BassBoost, "BassBoost")
    VGC_ENUM_VALUE(BassUp, "BassUp")
    VGC_ENUM_VALUE(BassDown, "BassDown")
    VGC_ENUM_VALUE(TrebleUp, "TrebleUp")
    VGC_ENUM_VALUE(TrebleDown, "TrebleDown")

    VGC_ENUM_VALUE(MediaPlay, "MediaPlay")
    VGC_ENUM_VALUE(MediaStop, "MediaStop")
    VGC_ENUM_VALUE(MediaPrevious, "MediaPrevious")
    VGC_ENUM_VALUE(MediaNext, "MediaNext")
    VGC_ENUM_VALUE(MediaRecord, "MediaRecord")
    VGC_ENUM_VALUE(MediaPause, "MediaPause")
    VGC_ENUM_VALUE(MediaTogglePlayPause, "MediaTogglePlayPause")

    VGC_ENUM_VALUE(HomePage, "HomePage")
    VGC_ENUM_VALUE(Favorites, "Favorites")
    VGC_ENUM_VALUE(Search, "Search")
    VGC_ENUM_VALUE(Standby, "Standby")
    VGC_ENUM_VALUE(OpenUrl, "OpenUrl")

    VGC_ENUM_VALUE(LaunchMail, "LaunchMail")
    VGC_ENUM_VALUE(LaunchMedia, "LaunchMedia")
    VGC_ENUM_VALUE(Launch0, "Launch0")
    VGC_ENUM_VALUE(Launch1, "Launch1")
    VGC_ENUM_VALUE(Launch2, "Launch2")
    VGC_ENUM_VALUE(Launch3, "Launch3")
    VGC_ENUM_VALUE(Launch4, "Launch4")
    VGC_ENUM_VALUE(Launch5, "Launch5")
    VGC_ENUM_VALUE(Launch6, "Launch6")
    VGC_ENUM_VALUE(Launch7, "Launch7")
    VGC_ENUM_VALUE(Launch8, "Launch8")
    VGC_ENUM_VALUE(Launch9, "Launch9")
    VGC_ENUM_VALUE(LaunchA, "LaunchA")
    VGC_ENUM_VALUE(LaunchB, "LaunchB")
    VGC_ENUM_VALUE(LaunchC, "LaunchC")
    VGC_ENUM_VALUE(LaunchD, "LaunchD")
    VGC_ENUM_VALUE(LaunchE, "LaunchE")
    VGC_ENUM_VALUE(LaunchF, "LaunchF")
    VGC_ENUM_VALUE(MonBrightnessUp, "MonBrightnessUp")
    VGC_ENUM_VALUE(MonBrightnessDown, "MonBrightnessDown")
    VGC_ENUM_VALUE(KeyboardLightOnOff, "KeyboardLightOnOff")
    VGC_ENUM_VALUE(KeyboardBrightnessUp, "KeyboardBrightnessUp")
    VGC_ENUM_VALUE(KeyboardBrightnessDown, "KeyboardBrightnessDown")
    VGC_ENUM_VALUE(PowerOff, "PowerOff")
    VGC_ENUM_VALUE(WakeUp, "WakeUp")
    VGC_ENUM_VALUE(Eject, "Eject")
    VGC_ENUM_VALUE(ScreenSaver, "ScreenSaver")
    VGC_ENUM_VALUE(WWW, "WWW")
    VGC_ENUM_VALUE(Memo, "Memo")
    VGC_ENUM_VALUE(LightBulb, "LightBulb")
    VGC_ENUM_VALUE(Shop, "Shop")
    VGC_ENUM_VALUE(History, "History")
    VGC_ENUM_VALUE(AddFavorite, "AddFavorite")
    VGC_ENUM_VALUE(HotLinks, "HotLinks")
    VGC_ENUM_VALUE(BrightnessAdjust, "BrightnessAdjust")
    VGC_ENUM_VALUE(Finance, "Finance")
    VGC_ENUM_VALUE(Community, "Community")
    VGC_ENUM_VALUE(AudioRewind, "AudioRewind")
    VGC_ENUM_VALUE(BackForward, "BackForward")
    VGC_ENUM_VALUE(ApplicationLeft, "ApplicationLeft")
    VGC_ENUM_VALUE(ApplicationRight, "ApplicationRight")
    VGC_ENUM_VALUE(Book, "Book")
    VGC_ENUM_VALUE(CD, "CD")
    VGC_ENUM_VALUE(Calculator, "Calculator")
    VGC_ENUM_VALUE(ToDoList, "ToDoList")
    VGC_ENUM_VALUE(ClearGrab, "ClearGrab")
    VGC_ENUM_VALUE(Close, "Close")
    VGC_ENUM_VALUE(Copy, "Copy")
    VGC_ENUM_VALUE(Cut, "Cut")
    VGC_ENUM_VALUE(Display, "Display")
    VGC_ENUM_VALUE(DOS, "DOS")
    VGC_ENUM_VALUE(Documents, "Documents")
    VGC_ENUM_VALUE(Excel, "Excel")
    VGC_ENUM_VALUE(Explorer, "Explorer")
    VGC_ENUM_VALUE(Game, "Game")
    VGC_ENUM_VALUE(Go, "Go")
    VGC_ENUM_VALUE(ITouch, "ITouch")
    VGC_ENUM_VALUE(LogOff, "LogOff")
    VGC_ENUM_VALUE(Market, "Market")
    VGC_ENUM_VALUE(Meeting, "Meeting")
    VGC_ENUM_VALUE(MenuKB, "MenuKB")
    VGC_ENUM_VALUE(MenuPB, "MenuPB")
    VGC_ENUM_VALUE(MySites, "MySites")
    VGC_ENUM_VALUE(News, "News")
    VGC_ENUM_VALUE(OfficeHome, "OfficeHome")
    VGC_ENUM_VALUE(Option, "Option")
    VGC_ENUM_VALUE(Paste, "Paste")
    VGC_ENUM_VALUE(Phone, "Phone")
    VGC_ENUM_VALUE(Calendar, "Calendar")
    VGC_ENUM_VALUE(Reply, "Reply")
    VGC_ENUM_VALUE(Reload, "Reload")
    VGC_ENUM_VALUE(RotateWindows, "RotateWindows")
    VGC_ENUM_VALUE(RotationPB, "RotationPB")
    VGC_ENUM_VALUE(RotationKB, "RotationKB")
    VGC_ENUM_VALUE(Save, "Save")
    VGC_ENUM_VALUE(Send, "Send")
    VGC_ENUM_VALUE(Spell, "Spell")
    VGC_ENUM_VALUE(SplitScreen, "SplitScreen")
    VGC_ENUM_VALUE(Support, "Support")
    VGC_ENUM_VALUE(TaskPane, "TaskPane")
    VGC_ENUM_VALUE(Terminal, "Terminal")
    VGC_ENUM_VALUE(Tools, "Tools")
    VGC_ENUM_VALUE(Travel, "Travel")
    VGC_ENUM_VALUE(Video, "Video")
    VGC_ENUM_VALUE(Word, "Word")
    VGC_ENUM_VALUE(Xfer, "Xfer")
    VGC_ENUM_VALUE(ZoomIn, "ZoomIn")
    VGC_ENUM_VALUE(ZoomOut, "ZoomOut")
    VGC_ENUM_VALUE(Away, "Away")
    VGC_ENUM_VALUE(Messenger, "Messenger")
    VGC_ENUM_VALUE(WebCam, "WebCam")
    VGC_ENUM_VALUE(MailForward, "MailForward")
    VGC_ENUM_VALUE(Pictures, "Pictures")
    VGC_ENUM_VALUE(Music, "Music")
    VGC_ENUM_VALUE(Battery, "Battery")
    VGC_ENUM_VALUE(Bluetooth, "Bluetooth")
    VGC_ENUM_VALUE(WLAN, "WLAN")
    VGC_ENUM_VALUE(UWB, "UWB")
    VGC_ENUM_VALUE(AudioForward, "AudioForward")
    VGC_ENUM_VALUE(AudioRepeat, "AudioRepeat")
    VGC_ENUM_VALUE(AudioRandomPlay, "AudioRandomPlay")
    VGC_ENUM_VALUE(Subtitle, "Subtitle")
    VGC_ENUM_VALUE(AudioCycleTrack, "AudioCycleTrack")
    VGC_ENUM_VALUE(Time, "Time")
    VGC_ENUM_VALUE(Hibernate, "Hibernate")
    VGC_ENUM_VALUE(View, "View")
    VGC_ENUM_VALUE(TopMenu, "TopMenu")
    VGC_ENUM_VALUE(PowerDown, "PowerDown")
    VGC_ENUM_VALUE(Suspend, "Suspend")
    VGC_ENUM_VALUE(ContrastAdjust, "ContrastAdjust")
    VGC_ENUM_VALUE(LaunchG, "LaunchG")
    VGC_ENUM_VALUE(LaunchH, "LaunchH")
    VGC_ENUM_VALUE(TouchpadToggle, "TouchpadToggle")
    VGC_ENUM_VALUE(TouchpadOn, "TouchpadOn")
    VGC_ENUM_VALUE(TouchpadOff, "TouchpadOff")
    VGC_ENUM_VALUE(MicMute, "MicMute")
    VGC_ENUM_VALUE(Red, "Red")
    VGC_ENUM_VALUE(Green, "Green")
    VGC_ENUM_VALUE(Yellow, "Yellow")
    VGC_ENUM_VALUE(Blue, "Blue")
    VGC_ENUM_VALUE(ChannelUp, "ChannelUp")
    VGC_ENUM_VALUE(ChannelDown, "ChannelDown")
    VGC_ENUM_VALUE(Guide, "Guide")
    VGC_ENUM_VALUE(Info, "Info")
    VGC_ENUM_VALUE(Settings, "Settings")
    VGC_ENUM_VALUE(MicVolumeUp, "MicVolumeUp")
    VGC_ENUM_VALUE(MicVolumeDown, "MicVolumeDown")
    VGC_ENUM_VALUE(New, "New")
    VGC_ENUM_VALUE(Open, "Open")
    VGC_ENUM_VALUE(Find, "Find")
    VGC_ENUM_VALUE(Undo, "Undo")
    VGC_ENUM_VALUE(Redo, "Redo")

    VGC_ENUM_VALUE(AltGr, "AltGr")
    VGC_ENUM_VALUE(MultiKey, "MultiKey")
    VGC_ENUM_VALUE(CodeInput, "CodeInput")
    VGC_ENUM_VALUE(SingleCandidate, "SingleCandidate")
    VGC_ENUM_VALUE(MultipleCandidate, "MultipleCandidate")
    VGC_ENUM_VALUE(PreviousCandidate, "PreviousCandidate")
    VGC_ENUM_VALUE(ModeSwitch, "ModeSwitch")

    VGC_ENUM_VALUE(Kanji, "Kanji")
    VGC_ENUM_VALUE(Muhenkan, "Muhenkan")
    VGC_ENUM_VALUE(Henkan, "Henkan")
    VGC_ENUM_VALUE(Romaji, "Romaji")
    VGC_ENUM_VALUE(Hiragana, "Hiragana")
    VGC_ENUM_VALUE(Katakana, "Katakana")
    VGC_ENUM_VALUE(HiraganaKatakana, "HiraganaKatakana")
    VGC_ENUM_VALUE(Zenkaku, "Zenkaku")
    VGC_ENUM_VALUE(Hankaku, "Hankaku")
    VGC_ENUM_VALUE(ZenkakuHankaku, "ZenkakuHankaku")
    VGC_ENUM_VALUE(Touroku, "Touroku")
    VGC_ENUM_VALUE(Massyo, "Massyo")
    VGC_ENUM_VALUE(KanaLock, "KanaLock")
    VGC_ENUM_VALUE(KanaShift, "KanaShift")
    VGC_ENUM_VALUE(EisuShift, "EisuShift")
    VGC_ENUM_VALUE(EisuToggle, "EisuToggle")
    VGC_ENUM_VALUE(Hangul, "Hangul")
    VGC_ENUM_VALUE(HangulStart, "HangulStart")
    VGC_ENUM_VALUE(HangulEnd, "HangulEnd")
    VGC_ENUM_VALUE(HangulHanja, "HangulHanja")
    VGC_ENUM_VALUE(HangulJamo, "HangulJamo")
    VGC_ENUM_VALUE(HangulRomaja, "HangulRomaja")
    VGC_ENUM_VALUE(HangulJeonja, "HangulJeonja")
    VGC_ENUM_VALUE(HangulBanja, "HangulBanja")
    VGC_ENUM_VALUE(HangulPreHanja, "HangulPreHanja")
    VGC_ENUM_VALUE(HangulPostHanja, "HangulPostHanja")
    VGC_ENUM_VALUE(HangulSpecial, "HangulSpecial")

    VGC_ENUM_VALUE(DeadGrave, "DeadGrave")
    VGC_ENUM_VALUE(DeadAcute, "DeadAcute")
    VGC_ENUM_VALUE(DeadCircumflex, "DeadCircumflex")
    VGC_ENUM_VALUE(DeadTilde, "DeadTilde")
    VGC_ENUM_VALUE(DeadMacron, "DeadMacron")
    VGC_ENUM_VALUE(DeadBreve, "DeadBreve")
    VGC_ENUM_VALUE(DeadAboveDot, "DeadAboveDot")
    VGC_ENUM_VALUE(DeadDiaeresis, "DeadDiaeresis")
    VGC_ENUM_VALUE(DeadAboveRing, "DeadAboveRing")
    VGC_ENUM_VALUE(DeadDoubleAcute, "DeadDoubleAcute")
    VGC_ENUM_VALUE(DeadCaron, "DeadCaron")
    VGC_ENUM_VALUE(DeadCedilla, "DeadCedilla")
    VGC_ENUM_VALUE(DeadOgonek, "DeadOgonek")
    VGC_ENUM_VALUE(DeadIota, "DeadIota")
    VGC_ENUM_VALUE(DeadVoicedSound, "DeadVoicedSound")
    VGC_ENUM_VALUE(DeadSemiVoicedSound, "DeadSemiVoicedSound")
    VGC_ENUM_VALUE(DeadBelowDot, "DeadBelowDot")
    VGC_ENUM_VALUE(DeadHook, "DeadHook")
    VGC_ENUM_VALUE(DeadHorn, "DeadHorn")
    VGC_ENUM_VALUE(DeadStroke, "DeadStroke")
    VGC_ENUM_VALUE(DeadAboveComma, "DeadAboveComma")
    VGC_ENUM_VALUE(DeadAboveReversedComma, "DeadAboveReversedComma")
    VGC_ENUM_VALUE(DeadDoubleGrave, "DeadDoubleGrave")
    VGC_ENUM_VALUE(DeadBelowRing, "DeadBelowRing")
    VGC_ENUM_VALUE(DeadBelowMacron, "DeadBelowMacron")
    VGC_ENUM_VALUE(DeadBelowCircumflex, "DeadBelowCircumflex")
    VGC_ENUM_VALUE(DeadBelowTilde, "DeadBelowTilde")
    VGC_ENUM_VALUE(DeadBelowBreve, "DeadBelowBreve")
    VGC_ENUM_VALUE(DeadBelowDiaeresis, "DeadBelowDiaeresis")
    VGC_ENUM_VALUE(DeadInvertedBreve, "DeadInvertedBreve")
    VGC_ENUM_VALUE(DeadBelowComma, "DeadBelowComma")
    VGC_ENUM_VALUE(DeadCurrency, "DeadCurrency")
    VGC_ENUM_VALUE(Deada, "Deada")
    VGC_ENUM_VALUE(DeadA, "DeadA")
    VGC_ENUM_VALUE(Deade, "Deade")
    VGC_ENUM_VALUE(DeadE, "DeadE")
    VGC_ENUM_VALUE(Deadi, "Deadi")
    VGC_ENUM_VALUE(DeadI, "DeadI")
    VGC_ENUM_VALUE(Deado, "Deado")
    VGC_ENUM_VALUE(DeadO, "DeadO")
    VGC_ENUM_VALUE(Deadu, "Deadu")
    VGC_ENUM_VALUE(DeadU, "DeadU")
    VGC_ENUM_VALUE(DeadSmallSchwa, "DeadSmallSchwa")
    VGC_ENUM_VALUE(DeadCapitalSchwa, "DeadCapitalSchwa")
    VGC_ENUM_VALUE(DeadGreek, "DeadGreek")
    VGC_ENUM_VALUE(DeadLowLine, "DeadLowLine")
    VGC_ENUM_VALUE(DeadAboveVerticalLine, "DeadAboveVerticalLine")
    VGC_ENUM_VALUE(DeadBelowVerticalLine, "DeadBelowVerticalLine")
    VGC_ENUM_VALUE(DeadLongSolidusOverlay, "DeadLongSolidusOverlay")

    VGC_ENUM_VALUE(MediaLast, "MediaLast")
    VGC_ENUM_VALUE(Select, "Select")
    VGC_ENUM_VALUE(Yes, "Yes")
    VGC_ENUM_VALUE(No, "No")
    VGC_ENUM_VALUE(Cancel, "Cancel")
    VGC_ENUM_VALUE(Printer, "Printer")
    VGC_ENUM_VALUE(Execute, "Execute")
    VGC_ENUM_VALUE(Sleep, "Sleep")
    VGC_ENUM_VALUE(Play, "Play")
    VGC_ENUM_VALUE(Zoom, "Zoom")
    VGC_ENUM_VALUE(Exit, "Exit")
    VGC_ENUM_VALUE(Context1, "Context1")
    VGC_ENUM_VALUE(Context2, "Context2")
    VGC_ENUM_VALUE(Context3, "Context3")
    VGC_ENUM_VALUE(Context4, "Context4")
    VGC_ENUM_VALUE(Call, "Call")
    VGC_ENUM_VALUE(Hangup, "Hangup")
    VGC_ENUM_VALUE(Flip, "Flip")
    VGC_ENUM_VALUE(ToggleCallHangup, "ToggleCallHangup")
    VGC_ENUM_VALUE(VoiceDial, "VoiceDial")
    VGC_ENUM_VALUE(LastNumberRedial, "LastNumberRedial")
    VGC_ENUM_VALUE(Camera, "Camera")
    VGC_ENUM_VALUE(CameraFocus, "CameraFocus")

    VGC_ENUM_VALUE(Unknown, "Unknown")
VGC_DEFINE_ENUM_END()

} // namespace vgc::ui
